name: Publish Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Build binaries
        run: docker build -t movies .

      - name: Copy binaries
        run: |
          BIN_FOLDER=/binaries
          CONTAINER_ID=$(docker create movies)
          docker cp $CONTAINER_ID:$BIN_FOLDER/movies-scrape movies-scrape
          docker cp $CONTAINER_ID:$BIN_FOLDER/movies-fill movies-fill
          docker cp $CONTAINER_ID:$BIN_FOLDER/display-movies-widget display-movies-widget
          docker cp $CONTAINER_ID:$BIN_FOLDER/icons icons

      - name: Bundle
        run: zip -r movies-cwb-arch-x64.zip movies-scrape movies-fill display-movies-widget icons bin/*

      - name: Release (versioned)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            movies-cwb-arch-x64.zip
            bin/install.sh

      - name: Update latest tag
        run: git push origin ${GITHUB_SHA}:refs/tags/latest --force

      - name: Release (latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: |
            movies-cwb-arch-x64.zip
            bin/install.sh